Repository jobda-keychain/jobda-qa-util-web, pull requests merged in 2022-01, with the labels that each got.

#8 Feat/account list item
  package-lock.json
  package.json
  src/components/AccountHeader/AccountHeader.tsx
  src/components/AccountHeader/style.tsx
  src/components/AccountRow/AccoutRow.tsx
  src/components/AccountRow/style.tsx
  src/lib/enum/platform.ts
  src/lib/enum/service.ts
  src/lib/enum/stage.ts
  src/style/Labels.tsx
  src/style/Row.tsx
  src/types/account.types.ts
  yarn.lock
Labels: enhancement

#15 Feat/main tab publishing
  package.json
  src/assets/Main/delete_tag.png
  src/assets/Main/index.ts
  src/assets/Main/logo.png
  src/assets/Main/setting.svg
  src/assets/index.ts
  src/components/MainHeader/MainHeader.tsx
  src/components/MainHeader/style.ts
  src/components/MainTab/MainTab.tsx
  src/components/MainTab/style.ts
  src/components/index.ts
  src/page/Main/Main.tsx
  src/style/GlobalStyle.ts
  src/types/envs.types.ts
  yarn.lock
Labels: enhancement

#19 Feat/seperate components
  src/components/MainFilter/MainFilter.tsx
  src/components/MainFilter/styles.ts
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/styles.ts
  src/components/MainTab/MainTab.tsx
  src/components/MainTab/style.ts
  src/components/index.ts
  src/page/Main/Main.tsx
  src/types/environment.types.ts
  src/types/envs.types.ts
  src/types/filter.types.ts
Labels: enhancement

#21 [MODIFY] 알아볼 수 없는 변수명 변경
  src/components/MainTab/MainTab.tsx
Labels: enhancement

#23 Feat/env management
  src/components/EnvSection/EnvSection.tsx
  src/components/EnvSection/style.ts
  src/components/MainFilter/MainFilter.tsx
  src/components/MainFilter/style.ts
  src/components/MainHeader/MainHeader.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/style.ts
  src/components/PublicHeader/PublicHeader.tsx
  src/components/PublicHeader/style.ts
  src/components/PublicTab/PublicTab.tsx
  src/components/PublicTab/style.ts
  src/components/index.ts
  src/page/EnvManagement/EnvManagement.tsx
  src/page/Main/Main.tsx
  src/route/MainRouter.tsx
Labels: enhancement

#28 Feat/pagination button Feat/place list in main
  src/components/PaginationButton/PaginationButton.tsx
Labels: enhancement

#29 [ADD] props
  src/components/PaginationButton/PaginationButton.tsx
Labels: enhancement

#37 Feat/login modal
  src/components/CopyModal/style.ts
  src/components/EnvironmentModal/EnvironmentModal.tsx
  src/components/EnvironmentModal/style.ts
  src/components/LoginModal/LoginModal.tsx
  src/components/LoginModal/style.ts
  src/style/GlobalStyle.ts
Labels: enhancement

#31 Feat/place list
  src/components/AccountList/AccoutRow.tsx
  src/components/EnvSection/EnvSection.tsx
  src/components/EnvironmentList/EnvironmentRow.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/style.ts
  src/components/PaginationButton/PaginationButton.tsx
  src/style/GlobalStyle.ts
  src/style/Section.tsx
Labels: enhancement

#36 Feat/delete modal
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/DeleteModal/style.ts
Labels: enhancement

#32 Feat/account modal publishing
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/EnvManagement/EnvSection/style.ts
  src/components/Main/MainFilter/MainFilter.tsx
  src/components/Main/MainFilter/style.ts
  src/components/Main/MainSection/MainSection.tsx
  src/components/Main/MainSection/style.ts
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/AccountModal/style.ts
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/DeleteModal/style.ts
  src/components/Public/PublicHeader/PublicHeader.tsx
  src/components/Public/PublicHeader/style.ts
  src/components/Public/PublicTab/PublicTab.tsx
  src/components/Public/PublicTab/style.ts
  src/components/index.ts
  src/style/GlobalStyle.ts
Labels: enhancement

#39 Feat/place modal
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/AccountModal/style.ts
  src/components/Public/PublicHeader/PublicHeader.tsx
  src/style/Modal.ts
Labels: enhancement

#41 Feat/place modal
  src/components/EnvManagement/EnvironmentList/EnvironmentRow.tsx
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/DeleteModal/style.ts
Labels: enhancement

#43 [CREATE] axios 파일 생성
  .gitignore
  src/util/api/Default/index.ts
Labels: enhancement

#44 Feat/create environment
  .gitignore
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/EnvManagement/EnvironmentList/EnvironmentRow.tsx
  src/components/EnvManagement/ServiceRadio/ServiceRadio.tsx
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/MainFilter/MainFilter.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/components/Public/PublicHeader/PublicHeader.tsx
  src/hooks/useEnvironmentList.ts
  src/hooks/useEnvironmentModal.ts
  src/hooks/useHeader.ts
  src/hooks/useModal.ts
  src/lib/enum/platform.ts
  src/style/Labels.tsx
  src/types/account.types.ts
  src/types/environment.types.ts
  src/types/filter.types.ts
  src/types/modal.types.ts
  src/util/api/environment/environment.api.ts
  src/util/api/environment/environment.request.ts
Labels: enhancement

#50 Feat/delete environment
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/hooks/useDeleteAccount.ts
  src/hooks/useDeleteEnvironment.ts
  src/types/modal.types.ts
  src/util/api/environment/environment.api.ts
Labels: enhancement

#48 Feat/modify environment
  src/hooks/useEnvironmentModal.ts
  src/util/api/environment/environment.api.ts
  src/util/api/environment/environment.request.ts
Labels: enhancement

#51 Feat/copy
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/CopyModal/CopyModal.tsx
  src/hooks/useCopy.ts
  src/types/modal.types.ts
Labels: enhancement

#55 Feat/get account list
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainFilter/MainFilter.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/AccountModal/style.ts
  src/components/Public/PaginationButton/PaginationButton.tsx
  src/components/Public/PublicTab/PublicTab.tsx
  src/hooks/useCopy.ts
  src/style/GlobalStyle.ts
  src/types/account.types.ts
  src/types/filter.types.ts
  src/util/api/AccountList/index.ts
  src/util/api/EnvironmentList/index.ts
Labels: enhancement

#58 [FIX] use call back
  src/components/Main/MainSection/MainSection.tsx
  src/hooks/useEnvironmentModal.ts
Labels: bug

#59 Feat/crud account
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/AccountModal/style.ts
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Public/PublicHeader/PublicHeader.tsx
  src/hooks/useDeleteAccount.ts
  src/models/request/index.ts
  src/models/response/index.ts
  src/models/vo/index.ts
  src/util/api/Account/index.ts
  src/util/api/AccountList/index.ts
Labels: enhancement

#61 Feat/fix modal
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/hooks/useCopy.ts
Labels: enhancement

#64 [ADD] cursor pointer 추가
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/AccountList/style.tsx
Labels: enhancement

#65 Feat/auto login
  package-lock.json
  package.json
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/EnvManagement/EnvironmentList/EnvironmentHeader.tsx
  src/components/EnvManagement/EnvironmentList/EnvironmentRow.tsx
  src/components/EnvManagement/ServiceRadio/ServiceRadio.tsx
  src/components/Main/AccountList/AccountHeader.tsx
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/components/Public/PaginationButton/PaginationButton.tsx
  src/components/Public/PublicHeader/PublicHeader.tsx
  src/hooks/useAutoLogin.ts
  src/page/Main/Main.tsx
  src/page/NotFound/NotFound.tsx
  yarn.lock
Labels: enhancement

#67 Feat/environment list
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainFilter/MainFilter.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/hooks/useDeleteEnvironment.ts
  src/hooks/useEnvironmentModal.ts
  src/models/request/index.ts
  src/models/response/index.ts
  src/types/filter.types.ts
  src/util/api/Account/index.ts
  src/util/api/EnvironmentList/index.ts
  src/util/api/environment/environment.request.ts
  src/util/api/environment/index.ts
Labels: enhancement

#71 Feat/logo on click
  src/components/Public/PublicHeader/PublicHeader.tsx
  src/components/Public/PublicHeader/style.ts
Labels: enhancement

#73 Feat/page reset
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainSection/MainSection.tsx
Labels: bug

#70 Feat/error message
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/AccountModal/style.ts
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/hooks/useEnvironmentModal.ts
  src/util/api/handleAxiosError.ts
Labels: enhancement

#76 [FIX] 페이지 전환 후 요소가 안 보이는 오류 수정
  src/components/Main/MainSection/MainSection.tsx
Labels: bug

#78 [FIX] 필터 추가 후 요소가 안 보이는 오류 수정
  src/components/Main/MainSection/MainSection.tsx
Labels: bug

#79 [ADD] get detail before copy
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/CopyModal/CopyModal.tsx
  src/hooks/useCopy.ts
Labels: enhancement

#80 Feat/list header
  src/components/EnvManagement/EnvironmentList/EnvironmentRow.tsx
  src/components/EnvManagement/EnvironmentList/style.ts
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/AccountList/style.tsx
  src/style/Row.tsx
Labels: enhancement

#81 Feat/reload
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
Labels: enhancement

#84 eslint warning 일부 해결
  src/hooks/useEnvironmentModal.ts
Labels: enhancement

#85 Feat/fix login
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/hooks/useAutoLogin.ts
  src/models/response/index.ts
  src/util/api/Account/index.ts
Labels: enhancement

#86 [ADD] refresh
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/hooks/useDeleteEnvironment.ts
  src/hooks/useEnvironmentModal.ts
Labels: enhancement

#87 [MODIFY] error message
  src/hooks/useEnvironmentModal.ts
Labels: enhancement

#88 [ADD] base name
  src/route/MainRouter.tsx
Labels: enhancement

#90 [ADD] 계정 상세보기 및 수정 시 환경을 가져오도록 추가
  src/components/Modal/AccountModal/AccountModal.tsx
Labels: enhancement

#93 [ADD] textarea에 maxLength 속성 추가
  src/components/Modal/AccountModal/AccountModal.tsx
Labels: enhancement

#94 Feat/delete error message
  package-lock.json
  package.json
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/DeleteModal/style.ts
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/hooks/useDeleteAccount.ts
  src/hooks/useDeleteEnvironment.ts
  src/hooks/useEnvironmentModal.ts
  src/route/MainRouter.tsx
  yarn.lock
Labels: enhancement

#96 [MODIFY] npm update
  package-lock.json
Labels: enhancement

#98 [MODIFY] build
  package.json
Labels: enhancement

#99 Develop
  package-lock.json
  package.json
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/DeleteModal/style.ts
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/hooks/useDeleteAccount.ts
  src/hooks/useDeleteEnvironment.ts
  src/hooks/useEnvironmentModal.ts
  src/route/MainRouter.tsx
  yarn.lock
Labels: enhancement

#100 [MODIFY] ci
  package.json
Labels: enhancement

#102 App version(0.2)
  package.json
Labels: enhancement

#104 [MODIFY] pacakge.json
  package.json
Labels: enhancement

#105 Feat/modify key name
  .github/workflows/main.yml
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/models/request/index.ts
  src/types/account.types.ts
Labels: enhancement

#106 [ADD] rtl, jest-dom
  package-lock.json
  package.json
  src/setupTests.js
  yarn.lock
Labels: enhancement

#108 [MODIFY] tab selected color 변경
  src/components/Public/PublicTab/style.ts
Labels: enhancement

#111 계정 생성에서 id가 입력되지 않는 오류 해결
  src/components/Modal/AccountModal/AccountModal.tsx
Labels: bug

#118 계정 삭제시 존재하지 않는 pk일 경우 아무 동작도 하지 않는 오류 수정
  src/hooks/useDeleteAccount.ts
Labels: bug

#119 Feat/client domain a
  package-lock.json
  package.json
  src/components/EnvManagement/EnvironmentList/EnvironmentRow.tsx
  src/components/EnvManagement/ServiceRadio/ServiceRadio.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/components/Modal/EnvironmentModal/style.ts
  src/hooks/useEnvironmentModal.ts
Labels: enhancement

#124 [MODIFY] expands clickable area
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/AccountList/style.tsx
  src/style/Row.tsx
Labels: enhancement

#125 Feat/modal error message
  src/components/EnvManagement/EnvironmentList/style.ts
  src/components/Main/AccountList/style.tsx
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/hooks/useEnvironmentModal.ts
Labels: enhancement

#126 필터 목록 가져오기 api 분리
  src/components/Modal/AccountModal/AccountModal.tsx
  src/util/api/Account/index.ts
Labels: enhancement

#120 Feat/copy
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/CopyModal/CopyModal.tsx
  src/components/Modal/CopyModal/style.ts
  src/hooks/useCopy.ts
  src/style/Modal.tsx
  src/types/account.types.ts
  src/util/api/Account/index.ts
Labels: enhancement

#128 App version(0.3)
  package-lock.json
  package.json
  src/components/EnvManagement/EnvironmentList/EnvironmentRow.tsx
  src/components/EnvManagement/EnvironmentList/style.ts
  src/components/EnvManagement/ServiceRadio/ServiceRadio.tsx
  src/components/Main/AccountList/AccoutRow.tsx
  src/components/Main/AccountList/style.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/CopyModal/CopyModal.tsx
  src/components/Modal/CopyModal/style.ts
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Modal/EnvironmentModal/EnvironmentModal.tsx
  src/components/Modal/EnvironmentModal/style.ts
  src/components/Public/PublicTab/style.ts
  src/hooks/useCopy.ts
  src/hooks/useDeleteAccount.ts
  src/hooks/useEnvironmentModal.ts
  src/models/request/index.ts
  src/setupTests.js
  src/style/Modal.tsx
  src/style/Row.tsx
  src/types/account.types.ts
  src/util/api/Account/index.ts
  yarn.lock
Labels: enhancement

#133 [ADD] text-wrap
  src/components/EnvManagement/EnvironmentList/style.ts
Labels: enhancement

#138 [ADD] min height
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/style/Section.tsx
Labels: enhancement

#139 [ADD] succes message
  package-lock.json
  package.json
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/CopyModal/style.ts
  src/hooks/useCopy.ts
Labels: enhancement

#142 Feat/exception of 404
  package-lock.json
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  yarn.lock
Labels: bug, enhancement

#143 [REMOVE] remove base name
  src/route/MainRouter.tsx
Labels: enhancement

#148 [MODIFY] delete environment title
  src/components/Modal/DeleteModal/DeleteModal.tsx
Labels: enhancement

#150 [ADD] avoid space
  src/components/Modal/AccountModal/AccountModal.tsx
  src/hooks/useEnvironmentModal.ts
Labels: enhancement

#153 App Version(0.4)
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainFilter/MainFilter.tsx
  src/components/Main/MainSection/MainSection.tsx
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/DeleteModal/DeleteModal.tsx
  src/components/Public/PublicTab/PublicTab.tsx
  src/hooks/useAccountReducer.ts
  src/hooks/useEnvironmentModal.ts
  src/types/account.types.ts
  src/types/action.types.ts
Labels: enhancement

#155 [ADD] div
  src/components/EnvManagement/EnvSection/EnvSection.tsx
  src/components/Main/MainSection/MainSection.tsx
Labels: enhancement

#157 [MODIFY] header
  src/components/EnvManagement/EnvironmentList/EnvironmentHeader.tsx
  src/components/EnvManagement/EnvironmentList/style.ts
  src/components/Main/AccountList/AccountHeader.tsx
  src/components/Main/AccountList/style.tsx
Labels: enhancement

#159 Feat/refactor code
  .github/workflows/main.yml
  src/App.tsx
  src/components/EnvManagement/EnvironmentSection/EnvironmentSection.tsx
  src/components/EnvManagement/EnvironmentSection/style.ts
  src/components/EnvManagement/index.ts
  src/components/Main/MainSection/MainSection.tsx
  src/components/Main/index.ts
  src/components/Modal/AccountModal/AccountModal.tsx
  src/components/Modal/index.ts
  src/components/Public/index.ts
  src/components/index.ts
  src/page/EnvManagement/EnvManagement.tsx
  src/page/Main/Main.tsx
  src/page/NotFound/NotFound.tsx
  src/route/MainRouter.tsx
Labels: documentation, enhancement

#161 [MODIFY] section height
  src/style/Section.tsx
Labels: enhancement

#163 Feat/bundle analyze
  package-lock.json
  package.json
  src/route/MainRouter.tsx
Labels: enhancement
